### ISSUE TITLE
compile err

### ISSUE THREAD

**Issue by Donnyjs** [Particle-Network/particle-ios#1]
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/107380127/175192180-147f084b-e5e8-475b-96c7-7ee8ce5ed875.png">

xcode version is 13.4.1   pod version is 1.11.3. 
I need help

**Comment by SunZhiC** [comment]
Please check your ParticleNetworkBase version in Podfile.lock, the latest version is 0.3.3.

**Comment by Donnyjs** [comment]
> Thank you ! I got it.
