### ISSUE TITLE
I  try to login, but I am failed.  What's the err param? 

### ISSUE THREAD

**Issue by Donnyjs** [Particle-Network/particle-ios#2]
<img width="385" alt="image" src="https://user-images.githubusercontent.com/107380127/175303702-ecbe7810-e307-482a-84a0-9fa75419a37c.png">

What's the invalid address

**Comment by pantaovay** [comment]
Config your app scheme url, select your app target, in the info section, click add URL Type, paste your scheme in URL Schemes. your scheme url should be "pn" + your project app id.

**Comment by SunZhiC** [comment]
Did you replace scheme with your project app uuid, the format is "pn" + your project app uuid, please follow Readme to configure it.
