### ISSUE TITLE
Pod install not working on Xcode 14

### ISSUE THREAD

**Issue by andresfilia** [Particle-Network/particle-ios#3]
When I run pod install using this Podfile
<img width="583" alt="Screenshot 2022-10-27 at 16 57 51" src="https://user-images.githubusercontent.com/93925490/198386384-a1a19d90-1a06-43b8-91fd-f9064d3ec323.png">

The Pods returns that error...
<img width="1172" alt="Screenshot 2022-10-27 at 16 56 27" src="https://user-images.githubusercontent.com/93925490/198386064-0276bc42-6e8b-4413-97fa-7436abf84ec9.png">

If I remove the specific version from `pod ParticleNetworkBase`, when I run the Project the Xcode returns this error:

`Module compiled with Swift 5.6.1 cannot be imported by the Swift 5.7 compiler: /Users/andre/Documents/XXX/xxx-ios/Pods/ParticleNetworkBase/Frameworks/ParticleNetworkBase.framework/Modules/ParticleNetworkBase.swiftmodule/arm64-apple-ios.swiftmodule`

![Screenshot 2022-10-27 at 17 03 16](https://user-images.githubusercontent.com/93925490/198387168-79c3ec69-1e20-463b-b16e-5f9e69252734.png)

**Comment by SunZhiC** [comment]
If you are using Xcode 14, you should specify version number in Podfile.
Remove Podfile.lock then execute 'pod install' in 
terminal again.

**Comment by andresfilia** [comment]
Thanks, It worked! I tried this yesterday but not working! Today it worked when I deleted the derived data to.

Thanks for your help.
