### ISSUE TITLE
The following error occurs when I run demo (Xcode 14.2, Apple M1 Max, Mac os 13.0.1 (22A400)

### ISSUE THREAD

**Issue by lceboy** [Particle-Network/particle-ios#4]
Undefined symbols for architecture x86_64:
  "_$sSa11CryptoSwifts5UInt8VRszlE8toBase64SSyF", referenced from:
      _$s19ParticleAuthService3WebC07prepareD033_0ECA0952FEFBFFC16C9FABE130FEA975LL4type4path6querysyAA0D11RequestTypeO_SSSDySSypGtF in ParticleAuthService(Web.o)
      _$s19ParticleAuthService3WebC04openD6WalletyyF in ParticleAuthService(Web.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by SunZhiC** [comment]
CryptoSwift new version cause this error. 
Work around, add these code to Podfile.

pod 'CryptoSwift', '1.6.0'

Fix CryptoSwift version to 1.6.0.

**Comment by SunZhiC** [comment]
As the error is fixed in 0.12.0, close the issue.
