### ISSUE TITLE
Very nice work, just a question, is Particle Network fully open source?

### ISSUE THREAD

**Issue by johnnynanjiang** [Particle-Network/particle-ios#5]

**Comment by SunZhiC** [comment]
iOS part is not open source.

**Comment by johnnynanjiang** [comment]
Thanks @SunZhiC 

It is understandable that iOS client is not open source, just wonder is there a list of all the open source parts.

e.g. we would like to build a crypto wallet based on Particle Network, and hopefully the underlying infrastructures are open source.

**Comment by SunZhiC** [comment]
> Thanks @SunZhiC
> 
> It is understandable that iOS client is not open source, just wonder is there a list of all the open source parts.
> 
> e.g. we would like to build a crypto wallet based on Particle Network, and hopefully the underlying infrastructures are open source.

Flutter part, react native part and unity part are open source, all the bridge files which pass messages from them to iOS or pass messages back are open source.
All iOS parts are XCFramework, it means close source.
