### ISSUE TITLE
Privacy updates for App Store submissions

### ISSUE THREAD

**Issue by hupengfei-hinterstellar** [Particle-Network/particle-ios#6]
Does Particle conform to Apple's privacy policy, and does the third-party SDKs referenced by Particle do?

https://developer.apple.com/news/?id=3d8a9yyh

**Comment by SunZhiC** [comment]
We will release new version adopt it.

**Comment by SunZhiC** [comment]
We have release new versions to adopt Apple Privacy Manifests.
