### ISSUE TITLE
API migration

### ISSUE THREAD

**Issue by hupengfei-hinterstellar** [Particle-Network/particle-ios#8]
In version 0.2.10, I use  BiconomyService setting with dappApiKeys.
```
BiconomyService.initialize(dappApiKeys: dappApiKeys)
```
Now how do I set the  "name" parameter of `AAService.initialize`?  

And some of the ChainInfo I used before couldn't find the corresponding in the new version.
```
ParticleNetwork.ChainInfo.ethereum(.goerli)
ParticleNetwork.ChainInfo.arbitrum(.goerli)
ParticleNetwork.ChainInfo.base(.testnet)
```

**Comment by SunZhiC** [comment]
Try ParticleNetwork.ChainInfo.ethereumSepolia, .baseSepolia, .arbitrumSepolia, and goerli is deprecated.

If you are using biconomy v1, you can init as the following code

```
// Initialize AA service
AAService.initialize(name: AA.AccountName.biconomyV1, biconomyApiKeys: [:])
// create a aa service
let aaService = AAService()
// set it to ParticleNetwork
ParticleNetwork.setAAService(aaService)
```

**Comment by hupengfei-hinterstellar** [comment]
> Try ParticleNetwork.ChainInfo.ethereumSepolia, .baseSepolia, .arbitrumSepolia, and goerli is deprecated.
> 
> If you are using biconomy v1, you can init as the following code
> 
> ```
> // Initialize AA service
> AAService.initialize(name: AA.AccountName.biconomyV1, biconomyApiKeys: [:])
> // create a aa service
> let aaService = AAService()
> // set it to ParticleNetwork
> ParticleNetwork.setAAService(aaService)
> ```

OK, I will try it
